### ISSUE TITLE
test.py报错

### ISSUE THREAD

**Issue by seogyt** [chrislinan/cx-extractor-python#1]
➜  cx-extractor-python-master python test.py 
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    s = cx.getText(content)
  File "/Users/darksola/Desktop/python/test/zhengwen/cx-extractor-python-master/CxExtractor.py", line 25, in getText
    self.__indexDistribution.clear()
AttributeError: 'list' object has no attribute 'clear'

**Comment by chrislinan** [comment]
@seogyt 代码第25行用的 ，list的clear方法是在Python3.3之后加入的，我开发测试用的Python 版本是Python 3.6。所以建议你使用最新的Python版本，或者参考[这里的解决方法](https://stackoverflow.com/questions/32055768/python3-attributeerror-list-object-has-no-attribute-clear) “In summary, it is the same as del l[:] and l[:] = [].”

**Comment by seogyt** [comment]
get，使用的python2.7，会采用3.3以上版本运行了。
