### ISSUE TITLE
如何直接读取json格式的html文本

### ISSUE THREAD

**Issue by susannah1993** [chrislinan/cx-extractor-python#4]
我看到CxExtractor.py中有readHtml这个函数，但是为什么我直接从文件中读取html数据（json格式）之后，再用filter_tags处理之后，得到结果还是带有标签的，而且最终getText结果为空。

**Comment by chrislinan** [comment]
@susannah1993 之前的设计应该是没有支持json格式的，你可以把这个文件发给我看一下么？ chrisbarry@sina.com

**Comment by susannah1993** [comment]
已经发到您的邮箱了，麻烦帮忙看一下原因，谢谢啦！

**Comment by chrislinan** [comment]
@susannah1993 首先你原始的json文件格式是错误的。你可以把这个文件内容全选复制到 http://www.bejson.com/ 检查一下看看能否解析。你文件的格式是 {} {} {} {} 你这里有100个单独的大括号， 但是正规的json 是这样写的  
```
[{
"id" : 1 ,
"name" : "xiaoming"
},{
"id" : 2 , 
"name" : "xiaohong"
}]
```

我不知道你这个json文件是用什么方法解析的，正常的解析器是不能识别的。

其次，你抽取出来的那个文件完全不是json的格式，但是为什么文件后缀要写成json？看上去是html格式，是很多html的网页写在了一个文件里，开头结尾都有html的tag，但是为什么所有的tag都要加个转义字符 "\\" ? 加了转义字符之后就不会被识别成html的标签，\<body\>\<\/body\> 这样的标签可以过滤掉，但是\<body\>\<\\/body\> 就不是正常的网页标签， 你这里所有的符号前面都加了转义字符，不知道是为啥

**Comment by susannah1993** [comment]
谢谢，我这个数据是每行一条html数据，是json格式的，那个“\”字符是反转义字符，我添加了一条判断就可以了，但是我发现这个很多网页最后输出都为空，提取不到正文，比如这个http://cdmd.cnki.com.cn/Article/CDMD-10007-1015809896.htm

**Comment by chrislinan** [comment]
@susannah1993 我调试发现，这个网页的原因是在过滤标签之后，网页里本来应该是空白行的地方会出现“ \r”这个字符，所以你可以自己在CxExtractor.py 文件的25行前面加这一行`lines[i] = lines[i].strip(' \r')` 。另外，因为这个网页过滤标签之后会有700多行，大部分是空白行，所以参数设置大一些才可以提取到`threshold=300,blocksWidth=10` 

这个链接提取出来的内容是这样的:

> 基于平行语料库的双语术语抽取
【摘要】：双语术语抽取是自然语言处理领域的一个重要课题,它被广泛地应用在机器翻译、信息抽取、双语信息检索、辅助机器翻译等方面。本文采用了基于平行语料库的双语术语抽取方法,该方法在单语术语抽取的基础上,从平行语料中统计出共现矩阵,再用相似度函数的方法生成对齐词典,最后抽取出互为翻译的术语对。论文主要工作包括:详细分析了基于平行语料库的双语术语抽取技术,介绍了目前常用的词对齐方法,并将单语抽取的候选术语看作是一个词,然后对语料进行编码,从而把短语对齐转化成了词对齐;详细介绍了四种相似度函数:Dice系数、χ2检验、对数释然比、互信息以及它们的优缺点。统计出平行语料中不同词和术语的共现矩阵,然后用相似度函数的方法计算相关度,生成对齐词典。同时分析此方法的不足,结合多种方法对此进行改善:(1)为减小单语抽取的不平衡,提出使用基于相同原理和方法的单语术语抽取工具;(2)针对中文多词术语到英文单词术语对齐准确率不高的情况,提出用HMM模型优化词对齐,提高了词对齐的准确度,进而提高了双语术语抽取的准确率。基于上述方法,开发了一个双语术语抽取系统,并做了三方面的实验:不同相似度函数对术语抽取正确率的影响、不同语料规模对术语抽取结果的影响、改进之后的方法对术语抽取结果的影响。实验发现:针对本文使用的语料,χ2检验是效果最好的相似度函数;随着语料规模的增大,双语术语抽取的准确率最开始快速提高,最后逐渐趋于稳定;使用HMM模型优化词对齐后,双语术语抽取的准确率提高了2.5%。本文开发的双语术语抽取系统,已经作为商品化软件,在华建IAT辅助翻译系统中投入实际应用。
【学位授予单位】：北京理工大学【学位级别】：硕士【学位授予年份】：2015【分类号】：TP391.1
更多同类文献
CAJ全文下载
(如何获取全文？ 欢迎：购买知网充值卡、在线充值、在线咨询)
CAJViewer阅读器支持CAJ、PDF文件格式
