### ISSUE TITLE
有关参数threshold和blocksWidth的问题

### ISSUE THREAD

**Issue by susannah1993** [chrislinan/cx-extractor-python#5]
我想问一下threshold和blocksWidth这两个参数都代表什么呢？threshold是对整个网页行数的限制？blocksWidth是对空白行的限制吗？我测试了一下这两个参数，对于我的数据当设置为（10,10）的时候抽取到的网页概率是最高的，但是在测试过程中当我把blocksWidth设置为3,4,5,6,7,8,和15,16的时候会报错，indexDistribution数组越界。想问一下这是什么原因呢？
还有个问题，这个算法可以保留正文内容中的一些结构吗？比如文中出现表格，可以保留整个表格的结构吗？

**Comment by chrislinan** [comment]
@susannah1993  blocksWidth表示行块宽度，意思是一个行块由多少行组成。threshold表示一个行块的长度如果没有超过这个值，就不会提取这个行块的内容，因为没有几个字符的行块可以认为不是正文。这个算法不支持保留表格结构。另外为什么把blocksWidth设置为3,4,5,6,7,8,和15,16的时候会报错，我要调试一下看看。你可以提供一下具体在提取哪个网页正文的时候，设置这些值会报错么？

**Comment by susannah1993** [comment]
好的，谢谢啦~数据我已经发到您的邮箱了~我把blocksWidth设置为8的时候在提取这个网页时报错https://peatix.com//event//128910，设置为15的时候在提取这个网页时报错https://ngu2015.challonge.com//zh_CN//SSBM_NGU2015
还想问一下，那您用过或者了解的有没有哪些网页正文提取算法是可以保留表格结构的？

**Comment by chrislinan** [comment]
@susannah1993 
1. 你这两个网页，https://ngu2015.challonge.com/zh_CN/SSBM_NGU2015 和 https://peatix.com/event/128910 都是没有正文的网页，所以提取不到，现在修改了代码提取不到的时候不会报错。
2. 没有用过

**Comment by susannah1993** [comment]
好的，谢谢啦~
