### ISSUE TITLE
如果采集网易的话，会出现长尾现象

### ISSUE THREAD

**Issue by fhg1225** [chrislinan/cx-extractor-python#7]
比如我直接采集http://tech.163.com/18/1018/07/DUCQHJJH00097U7T.html 这个页面，抽取的正文后面会出现：
500万辆产能的目标变得遥不可及。
 本文来源：第一财经 
 责任编辑：姚立伟_NT6056 
 财经 | 美国财政部未将中国列为汇率操纵国！ 原因详解
 科技 | 恒大法拉第陷员工合同纠纷 贾跃亭造车恐止步PPT

后面的列表也会包含近正文里面，请问，有可以调整的方式吗？

**Comment by chrislinan** [comment]
@fhg1225 
如果不设置参数，直接采集这个网页，是会出现长尾现象，比如下面代码
```
cx = CxExtractor()
html = cx.getHtml("http://tech.163.com/18/1018/07/DUCQHJJH00097U7T.html")
content = cx.filter_tags(html)
s = cx.getText(content)
print(s)
````
在结尾会输出如下内容：
本文来源：第一财经
 责任编辑：姚立伟_NT6056
 财经 | 收评：沪指走高涨4.09%重返2600 券商板块涨停
 科技 | 英特尔看好双显示屏设备：它会是个人电脑的未来吗
 体育 | 鲁尼梅开二度+19场造18球！率垫底队提前进季后赛
 娱乐 | 俞飞鸿与神秘男同居疑似隐婚？工作人员：瞎写的
 时尚 | 关晓彤公开减肥食谱，她们为了美什么都做得出来！
 车险:平安车险　人保车险　太平洋车险阳光车险　大地车险
 旅游险:国内游　境外游　申根保险　航空意外
 热门产品:综合意外险　资金账户安全险保险中老年意外险　驴友险　健康人寿险
热门点卡:问道　Q币　穿越火线　征途　龙之谷　56卡天龙八部2　5914卡　跑跑卡丁车　更多
热门公司:腾讯　巨人　盛大　金山　完美　搜狐九城　光宇　久游　世纪天成　更多
热门搜索:热血传奇　武林外传　赤壁
热门游戏:网易游戏
游戏充值:三分钟内到账，点卡充值最低7折起
 120117英特尔看好双显示屏设备：它会是个人电脑的未来吗
 218227如何能证明外星生物真的存在？科学家：拍张照片
 315903马蜂窝被曝点评造假，是行业原罪还是企业弊端
 412930创业不易，大特保创始人周磊因突发疾病不幸离世
 511457马蜂窝：点评非核心内容，自媒体报道有明显误导
 611003苹果"盗刷门"闹大了！中消协出手:该赔偿的就赔偿
 710189苹果公司要求彭博社撤回“中国恶意芯片”不实报道
 8842695后女生下晚班滴滴打车被带至墓园?警方介入调查

但是在调用的时候设置 threshold参数就可以避免这个问题：`cx = CxExtractor(threshold=186)`
